name: 'Inga'
description: 'Visualize code changes and impact on users'
inputs:
  language:
    description: 'Languages to be analyzed. ("java" | "typescript")'
    required: true
  root-path:
    description: 'Relative path of the project to be analyzed, so if you do not give this option, it defaults to the command execute path.'
    default: '.'
  exclude:
    description: 'Filenames of glob pattern matching to exclude from analysis. (e.g. "**/*.test.(ts|tsx)")'
    default: ''
  report-base:
    description: 'Set the base path for the HTML report. Set `<REPO>` if using GitHub Pages and the URL is `https://<USERNAME>.github.io/<REPO>/`.'
    default: '/'
runs:
  using: 'composite'
  steps:
    - uses: seachicken/inga-action/java@main
      if: ${{ inputs.language }} == 'java'
      with:
        root-path: ${{ inputs.root-path }}
        exclude: ${{ inputs.exclude }}
        github-token: ${{ github.token }}
    - uses: seachicken/inga-action/typescript@main
      if: ${{ inputs.language }} == 'typescript'
      with:
        root-path: ${{ inputs.root-path }}
        exclude: ${{ inputs.exclude }}
        github-token: ${{ github.token }}
    - name: Checkout inga-ui
      uses: actions/checkout@v3
      with:
        repository: seachicken/inga-ui
        path: inga
    - name: Build HTML reports
      working-directory: ./inga
      run: |
        npm ci
        npm_config_json="${GITHUB_WORKSPACE}/reports/report.json" npm run build -- --base=${{ inputs.report-base }}
      shell: bash
